from dna_operations import initial_vector_h0, dnamaj, dnach, nucleotide_list_from_nucleotide_string, nucleotide_addition
from dna_shifts import compute_wj, sum0, sum1
import random

k_values = [
    "CAAGGAGGAGTTGCGATCCTAGGAGGTGAGAG", "CTACATCTCACAGCACAGATTGTTCGCCTATC", "GTCCTAAATTGTTATTTGTACATCATGTAGTT",
    "TGGCGTCCTCGTGGCCGAACGAGCTCGTGTTA", "ATGCCCCGTAAGCCGTTTATCAGAGTCCATGA", "CCGCTTACACACTTACGTCGAACCTCAAACGC",
    "GCAGATTTGAAGGGCAGGTTACGCCATTGCGT", "GGGTACTACCTGTCCCTCGGCGTCGAACACGA", "TCGAAACTGGGGGCGAGGATAAATAAAGCAAG",
    "ACAGGAATCCGTAAACCACCCTAACGTTGTTG", "AGCAATACGACCGTTGCATGTGCAGTAGGATA", "CCCCAATACTTCTAATTCCCTTTTGTCATGAG",
    "CTAGGTTGCCTCCTCATTAGCTGTGAGCCGTT", "GAAATCTGGTACTTTGATGTACCGGCCGGTAC", "GCGTTCTAAACGGGCTAGCCTACTACAGATCC",
    "TAACGCGTTTACCTCATATTCGGCAGCGGCCA", "TGCAGCGTCGGCTAACGCTGTTACCAGGTCAG", "TGTTGTTGCACTGACGATGACATTAGCCTGAT",
    "AATTTAACGCTCTACGGAGTGATATCCCGTCC", "AGCAAATAGGACTATACTCTGGTAGCTACGCC", "AGTCTGGCAGTACGTTCCGCAGGTAAAGCTCC",
    "CAGGCTCAGACAGGGGCGTGGGCGTGCAGAAT", "CCTAGTAAGGGCTCTAGTTCCAACTTGTTCCA", "CTCGTTGCGAGATCGGGAATACACCCATGTCC",
    "GCGAATTGCCACCCAGTGTGCGCGTCTTGGGT", "GGGAATACTACGCGTCAGTCGTCAATAGACAA", "GTAAAAATAGCTTAGAGCGATTGTAGACATTT",
    "GTTTCCGCCTTTTACTGTTGTGTTAATGTGCA", "TACGTGAAAAGTTTATATTCGGGAGATTTAAG", "TCCCGGCTGCACCACTGCATAAGGGGCTAGCC",
    "AACGTAGGCGATCCACTGAAAAATGAAGCGTT", "ACCAAGGCAGGCCGCTAAGGAATGCGTGCTAA", "AGCTGTCTAAGGGACCCACGTCAGAGTTTTTA",
    "AGTGACGTAGACATGACCTAAGCGTAGCAGCG", "CATCAGTACGTCTTTACCGGTACAAGGGTGTC", "CCATATGAAATCACATGCTCGCCCGTATTCTT",
    "CGCCAAGGCTATCCCAGAGTGGTTCGATTCTG", "CTCGCGGGAAGGGTGTATTACTCTGTAGGGGA", "GAACTAAGTAGCAGTGCACTTGTCGGTGTGCG",
    "GCAGCTAGAGTAGACCACCAGAAGATCCATGT", "GGAGGTTTTGGAGGACCATATTACAAATCGCA", "GGGAACGGCGCGCAGTGTTACAAGATAAAAAC",
    "TAAGCAGTGAGTCTAATCAATTGAGCCTGCAC", "TACTCGTACCACGGATAACGCCCAGTTGATAA", "TCACGCAGTGGAACGCTCCGTGTTCCAGACGA",
    "TCCGGCGCAACGAGCACCCCCGCCGGGCACAA", "TTCAAATGATCCGACCCCCTCTACAGAAAGGG", "ACAACGGGGGAACTAAATAGGTGTTCACGTGA",
    "ACGCGGCATAACACCGGTGATCAGTCAATAGA", "ACTGATCTCGTAAAGACCACCAACGGGTCCAT", "AGCTCAGACTCTCATATCTTGATGTGGTGCGC",
    "ATCAGTAAGTTAGTCCTGACGCGTCAGAGGGA", "ATGCACTAAATAGTATTACCTAGCCCGGCGAT", "CATGTCGAGGGGCAGGTGATCAACGAGGTAGT",
    "CCGTGCTATAGGCATTCTCTCGATTGATCTAT", "CGGAAGTGCGTTTTATTCCGGTAGGTGAGGAT", "CTCAGATTGAAGTGTGCCTCTGTTGTAGTTTA",
    "CTGAGGCCCGATCGTTCAATACCTAGTTCGAA", "GACATAGACTGAACCAGGACTTAAGGGTCTAG", "GATATACTAAAGAAGAACGGCGCAATGCTGTA",
    "GCAAGTTGTTTTTTGGAGATCGATACTGAGGA", "GGCACCAACGTATGGTTCTGGAAGGTTCTGGC", "GTTGTTGCGGATTTCTGTAGTACGCTGCACCC",
    "TACGCTACCTGATTAGTGATCTAGCCATAGGT", "TAGGAGCTATTGTATGTGGGAGCGCGACGCTA", "TCACGACGGTGATACTAGACTAAATAAGAACT",
    "TGGGTCGGCTTCTCCGTATCTGAATGGTACTG", "TTCCCTTCCATTCTTTTGTGCGTGTCACCTGA", "AACGTTAACGCTGGGGCTAGACCTCGTTGTGG",
    "AAGGCGATCTTCTACCGGAGTAGAGCGAGGCG", "ACACATTTGCGAAACAGTTGTTGCAATCGGTG", "ACGTCTACAAGTATCCACATACTACACTACGT",
    "AGGATCGTCTCTTTCCAGATAACACTTCGACA", "ATAGTAGGGGGTCTGTCAAATACTAGCAGCAT", "ATTAGCTGGTTGAAGGACCCTAGCGTTGGTTA",
    "CAATACTCCGCTTACAGCTAACAAAATCCATA", "CATATACCTCCAGTTGTAGTATTGCAAGGTCG", "CCGCCTTTAGGCGCTATTTACGCCCTTGAGGG",
    "CCTTTAGTCGTTGGGTATGGTCCGTTGGTGTA", "CGTACACAACGCGATACAGGCACTCCGAACCT"
]


def sha512_hash(blocks):
    hi = initial_vector_h0

    for i, block in enumerate(blocks):
        r1, r2, r3, r4, r5, r6, r7, r8 = hi

        for j in range(80):
            k = nucleotide_list_from_nucleotide_string(k_values[j])
            t1 = r8
            temp = [sum1(r5), dnach(r5, r6, r7), k, compute_wj(block, j)]
            for t in temp:
                t1 = nucleotide_addition(t1, t)
            t2 = nucleotide_addition(sum0(r1), dnamaj(r1, r2, r3))
            r8, r7, r6, r5, r4, r3, r2, r1 = r7, r6, r5, nucleotide_addition(r4, t1), r3, r2, r1, nucleotide_addition(t1, t2)

        hi = [
            nucleotide_addition(r1, hi[0]), nucleotide_addition(r2, hi[1]),
            nucleotide_addition(r3, hi[2]), nucleotide_addition(r4, hi[3]),
            nucleotide_addition(r5, hi[4]), nucleotide_addition(r6, hi[5]),
            nucleotide_addition(r7, hi[6]), nucleotide_addition(r8, hi[7])
        ]

    return hi


nucleotides = ['A', 'C', 'T', 'G']
random_sequence = ''.join(random.choice(nucleotides) for _ in range(512))
print(random_sequence)
test_vector = [nucleotide_list_from_nucleotide_string(random_sequence)]

result = sha512_hash(test_vector)
print(result)
